### PR TITLE
Add option to invert the bootloader lines (RTS and DTR).

### PR DESCRIPTION
**Pull request by g-oikonomou**
After merging #50, #48 needs a rebase.

So I've done this rebase, I've removed some trailing whitespaces and excessive new line chars. I've also pythonised the logic that controls which pyserial function to call.

@peretuset @alignan does this work/break anything for you?

Closes #48

### CODE REVIEW

**Comment by alignan** [comment]
:+1:

````
$ python cc2538-bsl.py -b 115200 -e -w -v -a 0x00202000 zoul-demo.bin 
Opening port /dev/ttyUSB0, baud 115200
Reading data from zoul-demo.bin
Firmware file: Raw Binary
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 06:15:9B:5C:00:12:4B:00
Erasing 524288 bytes starting at address 0x00200000
    Erase done
Writing 516096 bytes starting at address 0x00202000
Write 8 bytes at 0x0027FFF8F00
    Write done                                
Verifying by comparing CRC32 calculations.
    Verified (match: 0x386141c5)
````

**Comment by peretuset** [comment]
Works fine for me too!
Pere

2016-02-25 22:50 GMT+01:00 Antonio Lignan <notifications@github.com>:

**Comment by g-oikonomou** [comment]
@JelmerT please review this one when you get a chance please instead of #48 and we'll be wanting to bump Contiki to this version when it gets merged.

**Comment by JelmerT** [comment]
Looks great! :+1: 

thanks

**Pull request merged**
