### PR TITLE
fix: cleanup imports of python-magic and IntelHex

### PR DESCRIPTION
**Pull request by smlng**
Moving optional imports of python-magic and IntelHex inline, with
error handling. Omitting state variables for cleaner code and better
readability.

### CODE REVIEW

**Comment by smlng** [comment]
@JelmerT can you test this with an actual device and with and w/o  the optional modules? I currently traveling and  do not have a cc2538 based board at hand :disappointed:

**Comment by JelmerT** [comment]
thanks for the PR @smlng , I have to dig up a dev-kit myself to test this, will try to check this week!
Code looks good at first sight, but I agree this needs an actual HW test

**Comment by fjmolinas** [comment]
@JelmerT how should this be tested? I have hardware available :)

**Comment by JelmerT** [comment]
@smlng this is real old, and i never got around to testing it, i do apologize for that!

This is a much better implementation, so I'm just pulling it, we'll hear quickly if things break or not.

Thanks so much for the PR!

**Pull request merged**
