### PR TITLE
fix: check force_speed by absence of property

### PR DESCRIPTION
**Pull request by git-developer**
Fix for https://github.com/JelmerT/cc2538-bsl/issues/162

### CODE REVIEW

**Comment by Ayush1325** [comment]
Found the problem. The force_speed property was originally set if `-b` was specified and was not a cli argument.

**Comment by git-developer** [comment]
Thanks for your quick response, @Ayush1325! I'd like to encourage you to open a PR and add the changes there. I will close this one then. The reason is that I cannot judge if the changes make sense or even are syntactically OK (I'm not a python developer).

If that is not acceptable for you, I can add patches to this PR. I'd like to ask you for the exact location and content of the code changes, preferably in patch format.

**Comment by git-developer** [comment]
I noticed one thing about your proposal: the default baud rate of `500000` is already set in [open()](https://github.com/git-developer/cc2538-bsl/blob/5ddd9c963a49c8dc20dc8b7f1530d3f93c148705/cc2538-bsl.py#L183). I suggest to avoid this duplication.

**Comment by git-developer** [comment]
Closed for https://github.com/JelmerT/cc2538-bsl/pull/165

**Comment by Ayush1325** [comment]
I have created a PR: https://github.com/JelmerT/cc2538-bsl/pull/165

While it is true that it is already set in `open()`, `args.baud` is being used at many other places and thus needs to be set. Also since baud is the 2nd argument of the function, the default value cannot be removed there without some refactoring. So I have moved the default baud to a global constant for now.

**Pull request closed without merging**
