### PR TITLE
Switch Python 3 only

### PR DESCRIPTION
**Pull request by smlng**
Switch to Python3 only, i.e. remove Python 2 specific stuff and adapt Travis accordingly.
Python 2 is deprecated and should not be used anymore

### CODE REVIEW

**Comment by JelmerT** [comment]
Thanks for the PR @smlng , i'm all for this 👍 

I did see another improvement over at RIOT on the script (No clue why they don't just add this repo as a submodule) 
Could you add that change to this PR too? https://github.com/RIOT-OS/RIOT/commit/ffc28c4b0f0ff7fa01990f5183e300af994c3886

**Comment by smlng** [comment]
> I did see another improvement over at RIOT on the script (No clue why they don't just add this repo as a submodule)

yep, as I'm with RIOT and saw that too, I was thinking in the same direction and would be in favour to add your repo instead of copying your script. Hence, this PR.

And yes I can add the reference commit here too, good idea.

**Comment by smlng** [comment]
btw. I think the fix in RIOT is not necessary bc when using python3 only it is not necessary to have this work around with bytearray. I'll try to clean this up and amend a commit here.

**Comment by JelmerT** [comment]
👍 great work

I'll bring up the submodule idea again om the RIOT side

this change might also be a good time for a version bump

**Comment by smlng** [comment]
> this change might also be a good time for a version bump

If you don't mind, I have some more ideas I'd like to add before releasing a new version, e.g.
- add flake8 checks
- switch to from `getopt` to `argparse`
 what do you think?

**Pull request merged**
