### PR TITLE
Switch to argparse

### PR DESCRIPTION
**Pull request by Ayush1325**
I have kept any changes not directly related to argparse out of this PR. However, switching to it should allow a lot more code cleaning in the future.

### CODE REVIEW

**Comment by JelmerT** [comment]
This one was long overdue and a great improvement, thanks so much!

**Comment by git-developer** [comment]
The type change of `port` is incompatible to previous versions, see https://github.com/JelmerT/cc2538-bsl/issues/161. What's the rationale behind this? The documentation was not updated.

**Comment by git-developer** [comment]
After looking at the code, I get the impression that this was not intended. The following types are set:

* `len`: int, had a number as default before => OK
* `baud`: int, had a number as default before => OK
* `address`: int, used `device.flash_start_addr` as default before which is a number => OK
* `port`: int, used as string in the code

Please confirm whether you regard https://github.com/JelmerT/cc2538-bsl/pull/163 as a valid fix.

**Comment by JelmerT** [comment]
Thanks for the catch and fix @git-developer, I definitely didn't test this PR enough before it was pulled, my bad.
But at least now it's in there and being tested ;)

**Pull request merged**
