### PR TITLE
cc2538-bsl: add -W,--write-erase to write and erase

### PR DESCRIPTION
**Pull request by fjmolinas**
This PR takes a similar approach as initially taken in  #87, I finally still find useful to let the script deal with finding out what sections need to be erased. So here I added the following option:

```
-W, --write-erase will erase flash pages where data will be written,
this avoids performing a mass erase.
```

### CODE REVIEW

**Comment by fjmolinas** [comment]
What do you think @JelmerT ?

**Comment by fjmolinas** [comment]
ping @JelmerT :)

**Comment by JelmerT** [comment]
Thanks for the PR @fjmolinas and your patience ;)

This looks ok at first sight, I'm concerned about the description of the command though. "write-erase" sounds like it would first write and then erase what it just wrote.

Would `erase_write` make more sense? And for description something like "Write after erasing section that will be written. Avoids mass erase."?

**Comment by fjmolinas** [comment]
> Thanks for the PR @fjmolinas and your patience ;)
> 
> This looks ok at first sight, I'm concerned about the description of the command though. "write-erase" sounds like it would first write and then erase what it just wrote.
> 
> Would `erase_write` make more sense? And for description something like "Write after erasing section that will be written. Avoids mass erase."?

You are right, I changed the name and amended the help message, let me know if it makes sense for you.

**Comment by fjmolinas** [comment]
I tested by checking by flashing two applications in the presence of a boot-loader that is kept in both cases (bootloader is in memory range 0x00200000 - 0x00201000)

```
creating /home/francisco/workspace/RIOT/tests/riotboot/bin/openmote-b/tests_riotboot-slot1.1611133614.riot.bin...
/home/francisco/workspace/RIOT/dist/tools/cc2538-bsl/cc2538-bsl.py  -a 0x00240000 -p "/dev/riot/tty-openmote-b" --bootloader-invert-lines --erase-write -v -b 460800 /home/francisco/workspace/RIOT/tests/riotboot/bin/openmote-b/tests_riotboot-slot1.1611133614.riot.bin
Opening port /dev/riot/tty-openmote-b, baud 460800
Reading data from /home/francisco/workspace/RIOT/tests/riotboot/bin/openmote-b/tests_riotboot-slot1.1611133614.riot.bin
Cannot auto-detect firmware filetype: Assuming .bin
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:14:B5:B5:76
    Erase before write done                 
Writing 15036 bytes starting at address 0x00240000
Write 156 bytes at 0x00243A208
    Write done
    
> curslotnr
 curslotnr
Current slot=1
> curslothdr
 curslothdr
Image magic_number: 0x544f4952
Image Version: 0x6007f2ae
Image start address: 0x00240400
Header chksum: 0x5070f47b

> getslotaddr 0
 getslotaddr 0
Slot 0 address=0x00201400
> dumpaddrs
 dumpaddrs
slot 0: metadata: 0x201000 image: 0x00201400
slot 1: metadata: 0x240000 image: 0x00240400
> 
```

```
/home/francisco/workspace/RIOT/dist/tools/cc2538-bsl/cc2538-bsl.py  -a 0x00201000 -p "/dev/riot/tty-openmote-b" --bootloader-invert-lines --erase-write -v -b 460800 /home/francisco/workspace/RIOT/tests/riotboot/bin/openmote-b/tests_riotboot-slot0.1611133615.riot.bin
Opening port /dev/riot/tty-openmote-b, baud 460800
Reading data from /home/francisco/workspace/RIOT/tests/riotboot/bin/openmote-b/tests_riotboot-slot0.1611133615.riot.bin
Cannot auto-detect firmware filetype: Assuming .bin
Connecting to target...
CC2538 PG2.0: 512KB Flash, 32KB SRAM, CCFG at 0x0027FFD4
Primary IEEE Address: 00:12:4B:00:14:B5:B5:76
    Erase before write done                 
Writing 15036 bytes starting at address 0x00201000
Write 156 bytes at 0x00204A208
    Write done                              
make[1]: Leaving

>  
> curslotnr
 curslotnr
Current slot=0
> curslothdr
 curslothdr
Image magic_number: 0x544f4952
Image Version: 0x6007f2af
Image start address: 0x00201400
Header chksum: 0x70700479

> getslotaddr 0
 getslotaddr 0
Slot 0 address=0x00201400
> dumpaddrs
 dumpaddrs
slot 0: metadata: 0x201000 image: 0x00201400
slot 1: metadata: 0x240000 image: 0x00240400
> 
```

In both cases I'm flashing at an offset and not touching the previously flashed firmware.

**Comment by fjmolinas** [comment]
ping @JelmerT :)

**Comment by fjmolinas** [comment]
ping @JelmerT

**Comment by JelmerT** [comment]
Apologies @fjmolinas for the (extreme) long delay here, this is a great feature, should have been pulled way sooner.

Thanks!

**Pull request merged**
