### PR TITLE
fix: check force_speed

### PR DESCRIPTION
**Pull request by Ayush1325**
Fix for #162

### CODE REVIEW

**Comment by git-developer** [comment]
Wouldn't it be possible to remove the following code completely
```python
  force_speed = False

    if args.baud:
        force_speed = True
    else:
        args.baud = DEFAULT_BAUD

```

and replace

```python
        if not force_speed and device.has_cmd_set_xosc:
```
by 
```python
        if not args.baud and device.has_cmd_set_xosc:
```

?

`open()` already knows the default, and all remaining references to `args.baud` are in debug statements.

**Comment by JelmerT** [comment]
@Ayush1325 could you rebase and address @git-developer their comment?
Can we use the `default=` option from argparse to set the default instead of using the global define?

**Comment by Ayush1325** [comment]
@git-developer While your solution is correct, as you pointed out, args.baud is used by debug statements before the `None` check and I do not think printing None there is great.

@JelmerT Using the default is a bit problematic since it is not possible to know if the value was supplied by the user or set by Python, which the `if` statement on `force_speed` seems to need to know. Even trying to check if `args.baud == DEFAULT_VALUE` is useless since the user can actually pass in the default value, and the old code would still treat it as `force_speed`. Since I do not know the original intention well enough here, I  created this PR which should preserve the old behavior irrespective of your intention.

**Comment by JelmerT** [comment]
@Ayush1325 this looks good for now, we can always re-open at later date.

Thanks so much for the fix!

**Pull request merged**
