### PR TITLE
make code nearly pep8 compliant

### PR DESCRIPTION
**Pull request by aabadie**
Follow-up of a discussion on RIOT-OS here https://github.com/RIOT-OS/RIOT/pull/5784.
It appears the script has a lot of pep8 issues and is not compatible python 2 and python 3.

### CODE REVIEW

**Comment by kYc0o** [comment]
I can confirm this code works on Python 2 and 3 on a OS X environment.

**Comment by aabadie** [comment]
After looking at your travis CI configuration, the original code was python 3 compliant already. Consider this PR as only fixing pep8 issues.
There was also a more severe issue [here](https://github.com/JelmerT/cc2538-bsl/pull/58/files#diff-c264965f463aa6132fdb2b51467d7fc6R619)

**Comment by aabadie** [comment]
ping

**Comment by JelmerT** [comment]
Thanks for this PR, everything looks good at first sight. Will try some tests with hardware and get everything pulled before the weekend.

Does this PR also include the change to make python2.6 in travis happy again?

**Comment by kYc0o** [comment]
Yes, apparently [this line](https://github.com/JelmerT/cc2538-bsl/pull/58/files#diff-c264965f463aa6132fdb2b51467d7fc6L606) was the one failing on python2.6, but if you want to test it would be better.

Thanks!

**Comment by JelmerT** [comment]
Great! 
Could you update the PR with 2.6 in the travis.yml? Then we can immediately see if travis is happy.

**Comment by aabadie** [comment]
> Yes, apparently this line was the one failing on python2.6, but if you want to test it would be better.

There are other places of the code that would fail with python 2.6 : the actual use of the `format` function on strings is not python 2.6 compatible (but this is easy to fix) and there is also a problem of bytes manipulation that is harder to fix.

My actual position is to not put too much effort in maintaining compatibility with old python versions to encourage people switching to recent versions of Python. Especially which python 2.6 which lacks essential features that one can find in python 3 and 2.7, making the maintainer work even more complex. This package is already python 2.7 compatible which is enough I think.

**Pull request closed without merging**
