### PR TITLE
Trigger bootload with DTR and RTS lines

### PR DESCRIPTION
**Pull request by peretuset**
I have updated the cc2538-bsl.py script to support using the DTR and RTS lines to trigger the bootloading process. Would be happy to review the approach and integrate it if you consider it interesting to have such feature.

### CODE REVIEW

**Comment by bradjc** [comment]
This has been in the script since cd31c47b49278807e401bf617edb53245bd32ae4. Has anything changed? Also, it's a shame to lose the comment on https://github.com/JelmerT/cc2538-bsl/pull/18/files#diff-c264965f463aa6132fdb2b51467d7fc6L114

**Comment by peretuset** [comment]
Yes, the funcionality was indeed available but now it can be configured via command line parameters, not by default. This is because some boards may use it and some may not, so I think it is better to provide it as an option. Also, it may be necessary to properly set the DTR and RTS pins to make sure that the board comes out of reset when the bootloading is done.
However, I agree that it is a pitty that the comment on line 114 is gone. I will add it again and update the PR.

**Comment by JelmerT** [comment]
Thanks for this PR @peretuset.
We opted to do the pin toggle by default, and not have a separate option for it, because less options makes for a more user friendly script. Doing the pin toggle on hardware that doesn't support it has no effect and also doesn't do any harm (DTR and RTS are usually just not connected). And doing the toggle doesn't noticeably slow down the uploading process in any way.
Did you have trouble with the chip not coming out of reset after using the original script?

I currently don't have any cc2538 hardware close by but I'll test your way of toggling (having a bootloader start and stop) in a couple days and follow up on this.

**Comment by ppannuto** [comment]
Perhaps it makes the most sense to leave the pin toggling on by default but add an option that allows users to turn it off?

**Comment by JelmerT** [comment]
@peretuset did you in the mean time have any problems with the current implementation of the DTR/RTS pin toggle? It seems to me that after programming, the chip properly resets on its own without the need of an external toggle of the reset line.

@ppannuto if there is a platform that experiences problems because of the use of the DTR/RTS lines, I'm all for an option to disable the use of those pins in this script. But up until now I haven't come across or heard reports of a platform that is having trouble with this. So since I'd like to have the least amount of config options for the script, I rather not add that option right now.

**Comment by JelmerT** [comment]
Choosing to keep the option on by default, so closing this.

Willing to reconsider if there are good arguments to make it an option, just comment here.

Also have a look at #27 for comment on the default state of DTR and RTS pins when opening a port, which might cause problems for this feature.

**Pull request closed without merging**
