### PR TITLE
pr: add write_erase -W option

### PR DESCRIPTION
**Pull request by fjmolinas**
Hi, I'm using this script for flashing partial firmware updates on cc2538, but to be able to do this regularly the part of the flash to be written needs to be erased before hand. I propose adding a -W command that will erase the section to write to, and only that section.

What do you think? Can something like this be added? Cheers

Francisco

### CODE REVIEW

**Comment by fjmolinas** [comment]
@JelmerT ping!

**Comment by JelmerT** [comment]
Thanks for the ping and PR @fjmolinas !

Does this actually work as expected though? See #12 and #11 
What if the firmware you're trying to flash doesn't line up with single ﬂash page size (2KB)?

Any thoughts on implementing it this way: https://github.com/JelmerT/cc2538-bsl/pull/11#issuecomment-45966756 ?

**Comment by fjmolinas** [comment]
> What if the firmware you're trying to flash doesn't line up with single ﬂash page size (2KB)?

@JelmerT You are right, I think I didn't have a problem with that because in my specific usecase the firmware is always lined-up.

> Any thoughts on implementing it this way: #11 (comment) ?

I like your suggestion, I'll try to implement.

**Comment by fjmolinas** [comment]
@JelmerT It took me some time to find time for this, but I addressed your suggestions. You can know specify a page or address range to erase, by default it takes inputs as addresses, if pages are to be used the command must have a 'p' option, e.g.:

```
-E a,0x00000000,0x00001000,
-E 0x00000000,0x00001000,
-E a,0x00000000
-E 0x00000000
-E p,1,4
-E p,1
```

What do you think?

**Comment by JelmerT** [comment]
This is looking great @fjmolinas, thanks for taking the time to implement it!

This was a feature that was on the todo list for a long time now. Nice work!

**Comment by fjmolinas** [comment]
@JelmerT Thanks for the review!

**Pull request merged**
