### PR TITLE
Correct the packet format for cmdMemWrite

### PR DESCRIPTION
**Pull request by alexvlockwood-bes**
Hey, I've had a bit of an unusual use case for your script, and managed to test the "untested" `cmdMemWrite()`. The packet format wasn't correct and causes the interface to desync on 32-bit writes. The code in this PR is now tested for both 8-bit and 32-bit writes.

### CODE REVIEW

**Comment by JelmerT** [comment]
Sweet! Thanks for the PR!

Glad we can remove the `#untested`.

AFAIK that function isn't used anywhere in the script though, care to add the actual cmd line argument for it?

Pulling this regardless, thanks!

**Comment by alexvlockwood-bes** [comment]
Glad this could be helpful. Not sure I'll have the time to add a command line argument in the near future. I'm doing some slightly unusual things over the bootloader interface so I'm actually just importing your script as a module, I've never added one in the first place

**Comment by JelmerT** [comment]
No worries, I'll try to add one when I find some time.

You are making me curious about the "unusual things" you're doing with the bootloader interface though. Is it a project you can elaborate about?

**Comment by alexvlockwood-bes** [comment]
Nothing too flashy - just using it as an ersatz test interface by operating peripherals via memory accesses.

**Pull request merged**
