### PR TITLE
Add CC26xx support

### PR DESCRIPTION
**Pull request by g-oikonomou**
This adds CC26xx support in a separate branch `feature/CC26xx_support` until the two can be merged together. This branch will not support CC2538 though.

This branch is little behind master, hence the commits appear in the history here. I _think_ that if you manually move the branch forward to mirror master, the respective commits will disappear from the history here. Happy to rebase if they don't

### CODE REVIEW

**Comment by JelmerT** [comment]
This looks great! Thanks @g-oikonomou 

Since I still don't have any proper CC26xx hardware, I can't test this at this point. But because I consider this branch a dev-branch, I'll pull it without testing.

If anyone else can test this and runs into problems or has requests -> open an issue or add to #25 

I moved my branch forward up until the master, most commits disappeared, but for some reason the last one is still there (even though it's the same commit on both branches). We'll see what happens when i merge it ;)

Let's try not to diverge this and the master branch too much though, I do in the end want support for both chips in one script.

:+1:

**Comment by g-oikonomou** [comment]
Yes. Diverging. Bad.

It might be an idea to merge master into here so we can have the same READMEs. I should have done that in #29 to be honest, but I only just thought of it...

**Comment by JelmerT** [comment]
Err, good point.

Just chery picked 155c692 onto this branch manually. Fixed :see_no_evil:

**Comment by JelmerT** [comment]
Nope! Just had to rebase it against master with `--preserve-merges`. Much cleaner solution :+1:

**Pull request merged**
