### PR TITLE
Fixes issue #1533 on Contiki

### PR DESCRIPTION
**Pull request by PalmaITEM**
The issue in https://github.com/contiki-os/contiki/issues/1533

Is solved by adding the delay in the "invoke_bootloader" **after** the entire invoking sequence.

### CODE REVIEW

**Comment by g-oikonomou** [comment]
Sorry, I was perhaps not clear in the Contiki discussion.

We need _both_ delays - the first one exists for different reasons

**Comment by alignan** [comment]
Yes, we need both of them.  I can confirm this works.

The explanation is simple:  the on-board PIC detects the RTS/DTS sequence, waits a bit, then replicates onto the CC2538's PA3/RST.  We need this delay that was introduced by the VM USB forwarding and later by the intelhex and python-magic.

**Comment by PalmaITEM** [comment]
Understood, I fixed the pull. Sorry for mixing things.

**Comment by PalmaITEM** [comment]
Hi, I have an update on this issue/pull request.

Using a fresh ubuntu machine (native, not a VM), the same problem appeared.

Solutions:
- Increasing just slightly the sleeps (to 0.005)
- Keeping the sleeps as they were **but** installing python-magic (actually, the second sleep seems to be redundant when using python-magic)

**Pull request merged**
